import { Property } from '@/types';

export const topProperties: Property[] = [
  {
    id: 'commercial',
    title: 'Commercial Plots',
    description: 'Prime commercial plots in developing areas with high growth potential and excellent connectivity.',
    image: '/images/home-page/Top properties/image1.jpeg',
    link: '/projects?type=commercial',
    alt: 'Commercial plots for sale in prime locations',
    width: 500,
    height: 300,
  },
  {
    id: 'development',
    title: 'Development Plots',
    description: 'Ready-to-build residential plots with all amenities and infrastructure in place.',
    image: '/images/home-page/Top properties/image2.jpeg',
    link: '/projects?type=development',
    alt: 'Development plots with infrastructure ready for construction',
    width: 500,
    height: 300,
  },
  {
    id: 'residential',
    title: 'Residential Plots',
    description: 'Premium residential plots in gated communities with modern amenities and security.',
    image: '/images/home-page/Top properties/image3.webp',
    link: '/projects?type=residential',
    alt: 'Premium residential plots in gated communities',
    width: 500,
    height: 300,
  },
  {
    id: 'agriculture',
    title: 'Agriculture Lands',
    description: 'Fertile agricultural lands perfect for farming and long-term investment opportunities.',
    image: '/images/home-page/Top properties/image4.jpeg',
    link: '/projects?type=agriculture',
    alt: 'Fertile agricultural lands for sale',
    width: 500,
    height: 300,
  },
  {
    id: 'houses',
    title: 'Independent Houses',
    description: 'Luxury independent houses with modern architecture and premium finishes.',
    image: '/images/home-page/Top properties/image5.jpg',
    link: '/projects?type=houses',
    alt: 'Luxury independent houses with modern design',
    width: 500,
    height: 300,
  },
  {
    id: 'apartments',
    title: 'Residential Apartments',
    description: 'Modern apartments with world-class amenities in prime locations.',
    image: '/images/home-page/Top properties/image6.jpeg',
    link: '/projects?type=apartments',
    alt: 'Modern residential apartments with amenities',
    width: 500,
    height: 300,
  },
];
